name: Build and deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: gulp buildProduction

      - name: Checkout main branch
        run: |
          git fetch
          git checkout main

      - name: Copy build files
        run: |
          cp -r dist/* .

      - name: Setup git with token
        run: |
          git config --global user.name "Your GitHub Username"
          git config --global user.email "Your Email"
          git remote add origin-https https://github.com/RastNik/test-build.git
          git remote set-url --push origin-https "https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/RastNik/test-build.git"

      - name: Push to main branch
        run: |
          git push origin-https main
